// proto/battleship.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: battleship.proto

package battleshipgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleshipRelay_CreateGame_FullMethodName = "/battleship.BattleshipRelay/CreateGame"
	BattleshipRelay_JoinGame_FullMethodName   = "/battleship.BattleshipRelay/JoinGame"
	BattleshipRelay_GameStream_FullMethodName = "/battleship.BattleshipRelay/GameStream"
)

// BattleshipRelayClient is the client API for BattleshipRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattleshipRelayClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error)
	GameStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GameMessage, GameMessage], error)
}

type battleshipRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleshipRelayClient(cc grpc.ClientConnInterface) BattleshipRelayClient {
	return &battleshipRelayClient{cc}
}

func (c *battleshipRelayClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, BattleshipRelay_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleshipRelayClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGameResponse)
	err := c.cc.Invoke(ctx, BattleshipRelay_JoinGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleshipRelayClient) GameStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GameMessage, GameMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BattleshipRelay_ServiceDesc.Streams[0], BattleshipRelay_GameStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GameMessage, GameMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleshipRelay_GameStreamClient = grpc.BidiStreamingClient[GameMessage, GameMessage]

// BattleshipRelayServer is the server API for BattleshipRelay service.
// All implementations must embed UnimplementedBattleshipRelayServer
// for forward compatibility.
type BattleshipRelayServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error)
	GameStream(grpc.BidiStreamingServer[GameMessage, GameMessage]) error
	mustEmbedUnimplementedBattleshipRelayServer()
}

// UnimplementedBattleshipRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleshipRelayServer struct{}

func (UnimplementedBattleshipRelayServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedBattleshipRelayServer) JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedBattleshipRelayServer) GameStream(grpc.BidiStreamingServer[GameMessage, GameMessage]) error {
	return status.Error(codes.Unimplemented, "method GameStream not implemented")
}
func (UnimplementedBattleshipRelayServer) mustEmbedUnimplementedBattleshipRelayServer() {}
func (UnimplementedBattleshipRelayServer) testEmbeddedByValue()                         {}

// UnsafeBattleshipRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleshipRelayServer will
// result in compilation errors.
type UnsafeBattleshipRelayServer interface {
	mustEmbedUnimplementedBattleshipRelayServer()
}

func RegisterBattleshipRelayServer(s grpc.ServiceRegistrar, srv BattleshipRelayServer) {
	// If the following call panics, it indicates UnimplementedBattleshipRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleshipRelay_ServiceDesc, srv)
}

func _BattleshipRelay_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleshipRelayServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleshipRelay_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleshipRelayServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleshipRelay_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleshipRelayServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleshipRelay_JoinGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleshipRelayServer).JoinGame(ctx, req.(*JoinGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleshipRelay_GameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BattleshipRelayServer).GameStream(&grpc.GenericServerStream[GameMessage, GameMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleshipRelay_GameStreamServer = grpc.BidiStreamingServer[GameMessage, GameMessage]

// BattleshipRelay_ServiceDesc is the grpc.ServiceDesc for BattleshipRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleshipRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battleship.BattleshipRelay",
	HandlerType: (*BattleshipRelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _BattleshipRelay_CreateGame_Handler,
		},
		{
			MethodName: "JoinGame",
			Handler:    _BattleshipRelay_JoinGame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GameStream",
			Handler:       _BattleshipRelay_GameStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "battleship.proto",
}
