# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleship.proto

require 'google/protobuf'


descriptor_data = "\n\x10\x62\x61ttleship.proto\x12\nbattleship\"\x13\n\x11\x43reateGameRequest\"%\n\x12\x43reateGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"\"\n\x0fJoinGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\":\n\x10JoinGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x8d\x01\n\x0bGameMessage\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12/\n\x04\x61rgs\x18\x03 \x03(\x0b\x32!.battleship.GameMessage.ArgsEntry\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xe9\x01\n\x0f\x42\x61ttleshipRelay\x12K\n\nCreateGame\x12\x1d.battleship.CreateGameRequest\x1a\x1e.battleship.CreateGameResponse\x12\x45\n\x08JoinGame\x12\x1b.battleship.JoinGameRequest\x1a\x1c.battleship.JoinGameResponse\x12\x42\n\nGameStream\x12\x17.battleship.GameMessage\x1a\x17.battleship.GameMessage(\x01\x30\x01\x42\x31Z\"go.battleship/proto/battleshipgrpc\xea\x02\nBattleshipb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Battleship
  CreateGameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("battleship.CreateGameRequest").msgclass
  CreateGameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("battleship.CreateGameResponse").msgclass
  JoinGameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("battleship.JoinGameRequest").msgclass
  JoinGameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("battleship.JoinGameResponse").msgclass
  GameMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("battleship.GameMessage").msgclass
end
