# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: battleship.proto for package 'Battleship'
# Original file comments:
# proto/battleship.proto

require 'grpc'
require 'battleship_pb'

module Battleship
  module BattleshipRelay
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'battleship.BattleshipRelay'

      rpc :CreateGame, ::Battleship::CreateGameRequest, ::Battleship::CreateGameResponse
      rpc :JoinGame, ::Battleship::JoinGameRequest, ::Battleship::JoinGameResponse
      rpc :GameStream, stream(::Battleship::GameMessage), stream(::Battleship::GameMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
